### PR TITLE
Ossisfy readme

### PR DESCRIPTION
**Pull request by rod**
Add some OSS goodness to the readme

### CODE REVIEW

**Review by carlthuringer — APPROVED** [review]

**Comment by carlthuringer** [comment]
*standing ova-tion*

**Comment by sisk** [comment]
:man_facepalming:

**Comment by rod** [comment]
@sisk what?!

**Comment by sisk** [comment]
@rod: @carlthuringer's comment was pun-a-riffic!

**Comment by rod** [comment]
@sisk: I thought @carlthuringer's pun was egg-cellent

**Comment by sisk** [comment]
:man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming: :man_facepalming:

**Pull request merged**
